package enums

object State extends Enumeration {
	type State = Value
	
	val AL = Value(1,"Alabama")
	val AK = Value(2,"Alaska")
	val AZ = Value(3,"Arizona")
	val AR = Value(4,"Arkansas")
	val CA = Value(5,"California")
	val CO = Value(6,"Colorado")
	val CT = Value(7,"Connecticut")
	val DE = Value(8,"Delaware")
	val FL = Value(9,"Florida")
	val GA = Value(10,"Georgia")
	val HI = Value(11,"Hawaii")
	val ID = Value(12,"Idaho")
	val IL = Value(13,"Illinois")
	val IN = Value(14,"Indiana")
	val IA = Value(15,"Iowa")
	val KS = Value(16,"Kansas")
	val KY = Value(17,"Kentucky")
	val LA = Value(18,"Louisiana")
	val ME = Value(19,"Maine")
	val MD = Value(20,"Maryland")
	val MA = Value(21,"Massachusetts")
	val MI = Value(22,"Michigan")
	val MN = Value(23,"Minnesota")
	val MS = Value(24,"Mississippi")
	val MO = Value(25,"Missouri")
	val MT = Value(26,"Montana")
	val NE = Value(27,"Nebraska")
	val MV = Value(28,"Nevada")
	val NH = Value(29,"New Hampshire")
	val NJ = Value(30,"New Jersey")
	val NM = Value(31,"New Mexico")
	val NY = Value(32,"New York")
	val NC = Value(33,"North Carolina")
	val ND = Value(34,"North Dakota")
	val OH = Value(35,"Ohio")
	val OK = Value(36,"Oklahoma")
	val OR = Value(37,"Oregon")
	val PA = Value(38,"Pennsylvania")
	val RI = Value(39,"Rhode Island")
	val SC = Value(40,"South Carolina")
	val TN = Value(41,"Tennessee")
	val TX = Value(42,"Texas")
	val UT = Value(43,"Utah")
	val VT = Value(44,"Vermont")
	val VA = Value(45,"Virginia")
	val WA = Value(46,"Washington")
	val WV = Value(47,"West Virginia")
	val WI = Value(48,"Wisconsin")
	val WY = Value(49,"Wyoming")
	
}